accounts/urls.py
from django.urls import path

from accounts.views import (UsersLoginView, UsersLogoutView,
                            email_activate_view, users_signup_view, dashboard,
                            user_account_update_form, user_profile_update_form, user_social_form, PasswordChange,
                            PasswordChangeDone, PasswordReset, PasswordResetDone, PasswordResetConfirm,
                            PasswordResetComplete, UsersProfileView)
app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', users_signup_view, name="register"),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', email_activate_view, name='activate'),
    path('accounts/login/', UsersLoginView.as_view(), name='login'),
    path('accounts/logout/', UsersLogoutView.as_view(), name='logout'),
    path('accounts/account/update/', user_account_update_form, name='user_account_update_form'),
    path('accounts/profile/update/', user_profile_update_form, name='user_profile_update_form'),
    path('accounts/social/update/', user_social_form, name='user_social_form'),
    path('accounts/password/change/', PasswordChange.as_view(), name='password_change'),
    path('accounts/password/change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('accounts/password/reset/', PasswordReset.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', PasswordResetDone.as_view(), name='reset_done'),
    path('accounts/password/reset/complete/', PasswordResetComplete.as_view(), name='reset_complete'),
    path('accounts/password/reset/confirm/<uidb64>/<token>', PasswordResetConfirm.as_view(), name='reset_confirm'),
    path('author/<str:username>/', UsersProfileView.as_view(), name='profile'),
    path('dashboard/', dashboard, name='dashboard'),
]

courses/urls.py
from django.urls import path
from courses.views import CoursesCreateView, CoursesListView, CoursesUpdateView, CoursesDeleteView, \
    SearchView, course_detail

app_name = 'course'
urlpatterns = [
    path('', CoursesListView.as_view(), name="home"),
    path('courses/', CoursesListView.as_view(), name="courses"),
    path('courses/<slug:slug>/', course_detail, name="course_detail"),
    # path('courses/<slug:slug>/', CoursesDetailView.as_view(), name="course_detail"),
    path('create/', CoursesCreateView.as_view(), name="course_create"),
    path('courses/update/<slug:slug>/', CoursesUpdateView.as_view(), name="course_update"),
    path('courses/delete/<slug:slug>/', CoursesDeleteView.as_view(), name="course_delete"),
    path('search/', SearchView.as_view(), name="search"),
]

tinymce/urls.py
from django.conf.urls import url
from .views import spell_check, filebrowser, css, spell_check_callback

urlpatterns = [
    url(r'^spellchecker/$', spell_check, name='tinymce-spellchecker'),
    url(r'^filebrowser/$', filebrowser, name='tinymce-filebrowser'),
    url(r'^tinymce4.css', css, name='tinymce-css'),
    url(r'^spellcheck-callback.js', spell_check_callback, name='tinymce-spellcheck-callback')
]

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = ProcessedImageField(default='profile_avatar.png',
                                 upload_to='users_avatar', format='png',
                                 processors=[ResizeToFill(50, 50)],
                                 options={'quality': 80}, blank=True)
    avatar_large = ImageSpecField(source='avatar',
                                  format='png',
                                  processors=[ResizeToFill(100, 100)],
                                  options={'quality': 80})
    bio = models.TextField(max_length=200, blank=True)
    profession = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=20, blank=True)

    def __str__(self):
        user_detail = '{} ({})'.format(self.user.username, self.user.email)
        return user_detail

    def get_location(self):
        return '{}, {}'.format(self.city, self.country)


class Social(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook = models.URLField()
    twitter = models.URLField()
    instagram = models.URLField()

    def __str__(self):
        return '{} {}'.format(self.user.get_full_name, 'socials')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from accounts.models import Profile, Social

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class SocialForm(forms.ModelForm):
    class Meta:
        model = Social
        exclude = ['user']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from accounts.forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm, SocialForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from accounts.models import Social
from courses.models import Courses, Comments
from .tokens import account_activation_token
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage
from django.contrib.auth.views import LogoutView, LoginView

User = get_user_model()


def users_signup_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('accounts/activate_email_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'accounts/email_sent.html')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})


def email_activate_view(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Thank you for confirming your email, you can now access your account.')

        return render(request, 'accounts/activation_success.html')
    else:
        messages.error(request, 'Activation error, Invalid link.')
        return render(request, 'accounts/activation_error.html')


class UsersLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('account')


class UsersLogoutView(LogoutView):
    template_name = 'accounts/logout.html'


class Dashboard(ListView):
    template_name = 'accounts/dashboard.html'

    def get_queryset(self):
        self.username = get_object_or_404(User, username=self.kwargs['username'])
        return Courses.objects.filter(author=self.username)

    def get_context_data(self, *args, **kwargs):
        context = super(Dashboard, self).get_context_data(*args, **kwargs)
        context['author_list'] = self.request.user


@login_required()
def dashboard(request):
    courses = request.user.courses_set.all().order_by('-published')
    context = {
        'courses': courses,
    }
    return render(request, 'accounts/dashboard.html', context)


class UsersProfileView(LoginRequiredMixin, ListView):
    template_name = 'base-user-profile.html'

    context_object_name = 'courses'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(username=self.kwargs['username'])
        return context

    def get_queryset(self):
        self.username = get_object_or_404(User, username=self.kwargs['username'])
        return Courses.objects.filter(author=self.username)


def user_account_update_form(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been updated')
            return redirect('accounts:dashboard')
            # return redirect('accounts:user_profile')
    else:
        form = UserUpdateForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update/edit_account_info.html', context)


def user_profile_update_form(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated')
            return redirect('accounts:dashboard')
    else:
        form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'form': form
    }
    return render(request, 'accounts/update/edit_profile_info.html', context)


def user_social_form(request):
    if request.method == 'POST':
        form = SocialForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your social profile has been updated')
            return redirect('accounts:dashboard')
    else:
        form = SocialForm(instance=request.user.profile)
    context = {
        'social': form
    }
    return render(request, 'accounts/social_form.html', context)


class ProfileBaseTemplateView(ListView):
    model = Social
    template_name = 'base-user-profile.html'


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password/change_password.html'
    success_url = reverse_lazy('accounts:password_change_done')


class PasswordChangeDone(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'accounts/password/change_password_done.html'


class PasswordReset(PasswordResetView):
    template_name = 'accounts/password/reset_password.html'
    success_url = reverse_lazy('accounts:reset_done')
    email_template_name = 'accounts/password/password_reset_email.html'


class PasswordResetDone(PasswordResetDoneView):
    template_name = 'accounts/password/reset_password_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    template_name = 'accounts/password/reset_password_confirm.html'
    success_url = reverse_lazy('accounts:reset_complete')


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'accounts/password/reset_password_complete.html'

templates/accounts/activate_email_account.html
{% autoescape off %}
Hi {{ user.username }},
Your account was successfully created. Please click below link to activate your account
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/activation_error.html
{% extends 'auth_base.html' %}
{% block auth %}
    {% block title %}<title>Account Activation Error </title>{% endblock title %}
{% block navbar %}
 {{ block.super }}
{% endblock navbar %}
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="login-reg-bg">
			<div class="log-reg-area">
				<h2 class="log-title">account activation error</h2>
				<form action="" method="post">
					<p>Invalid or expired activation link</p>
				</form>
			</div>
		</div>
	</div>
{% endblock auth %}

templates/accounts/activation_success.html
{% extends 'auth_base.html' %}
{% block auth %}
    {% block title %}<title>Account Activation Successful</title>{% endblock title %}
{% block navbar %}
 {{ block.super }}
{% endblock navbar %}
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="login-reg-bg">
			<div class="log-reg-area">
				<h2 class="log-title">account activated successfully</h2>
				<form action="" method="post">
					<p>You can now sign in to your account</p>
					<div class="submit-btns" >
						<a href="{% url 'accounts:login' %}"><button class=" btn btn-outline-primary" type="button">Sign in</button></a>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock auth %}

templates/accounts/dashboard.html
{% extends 'base-user-profile.html' %}
{% load static %}
{% block content %}
{% block title %}
    <title>Dashboard - {{ request.user.get_full_name|title }}</title>
{% endblock title %}
    <div class="col-lg-6">
        {% for course in courses %}
            <div class="central-meta item">
                <div class="user-post">
                    <div class="friend-info">
                        {% if course.author.profile.avatar %}
                            <figure>
                                <img src="{{ course.author.profile.avatar.url }}" alt="">
                            </figure>
                        {% else %}
                            <img src="{% static 'default.ico' %}" alt="">
                        {% endif %}
                            <div class="friend-name">
                            <ins><a href="{% url 'accounts:profile' course.author.username %}" title="">{{ course.author.get_full_name|title }}</a></ins>
                            <span>published: {{ course.published }}</span>
                            <span>last updated: {{ course.last_updated|timesince }} ago</span>
                        </div>
                        <div class="post-meta">
                            <img src="{{ course.cover.url }}" alt="">
                            <div class="we-video-info">
                                <ul>
                                    <li>
                                        <a href="{% url 'course:course_update' course.slug %}"><span class="" data-toggle="tooltip" title="">
                                            <i class="ti-write"></i>
                                            <ins>Update</ins>
                                        </span></a>
                                    </li>
                                    <li>
                                        <a href="{% url 'course:course_delete' course.slug %}"><span class="dislike" data-toggle="tooltip" title="">
                                            <i class="ti-trash"></i>
                                            <ins>Delete</ins>
                                        </span></a>
                                    </li>
                                    <li>
                                        <span class="views" data-toggle="tooltip" title="views">
                                            <i class="fa fa-eye"></i>
                                            <ins>1.2k</ins>
                                        </span>
                                    </li>
                                    <li>
                                        <span class="comment" data-toggle="tooltip" title="Comments">
                                            <i class="fa fa-comments-o"></i>
                                            <ins>{{ course.comments.count }}</ins>
                                        </span>
                                    </li>
                                    <li>
                                        <span class="like" data-toggle="tooltip" title="like">
                                            <i class="ti-heart"></i>
                                            <ins>2.2k</ins>
                                        </span>
                                    </li>
                                    <li>
                                        <span class="dislike" data-toggle="tooltip" title="dislike">
                                            <i class="ti-heart-broken"></i>
                                            <ins>200</ins>
                                        </span>
                                    </li>
                                    <li class="social-media">
                                        <div class="menu">
                                          <div class="btn trigger"><i class="fa fa-share-alt"></i></div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-html5"></i></a></div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-facebook"></i></a></div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-google-plus"></i></a></div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-twitter"></i></a></div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-css3"></i></a></div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-instagram"></i></a>
                                            </div>
                                          </div>
                                            <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-dribbble"></i></a>
                                            </div>
                                          </div>
                                          <div class="rotater">
                                            <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-pinterest"></i></a>
                                            </div>
                                          </div>

                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="friend-name">
                                <ins><a href="{{ course.get_absolute_url }}" title="">{{ course.title|title }}</a></ins>
                            </div>
                            <div class="description">
                                <p>
                                    {{ course.summary|capfirst }}
                                </p>
                            </div>
                        </div>
                    </div>
{#                    <div class="coment-area">#}
{#                        <ul class="we-comet">#}
{#                            {% for comment in course.comments.all %}#}
{#                                <li>#}
{#                                    <div class="comet-avatar">#}
{#                                        <img src="{{ comment.author.profile.avatar.url }}" alt="">#}
{#                                    </div>#}
{#                                    <div class="we-comment">#}
{#                                        <div class="coment-head">#}
{#                                            <h5><a href="{% url 'accounts:profile' comment.author.username %}" title="">{{ comment.author.get_full_name|title }}</a></h5>#}
{#                                            <span>1 year ago</span>#}
{#                                            <button type="button" name="button" class="reply-btn btn-primary btn-sm float-right" ><i>Reply</i></button>#}
{#                                        </div>#}
{#                                        <p>{{ comment.comment }}</p>#}
{#                                    </div>#}
{#                                        <ul class="replies" style="display: none">#}
{#                                            {% for reply in comment.reply.all %}#}
{#                                                <li>#}
{#                                                    <div class="comet-avatar">#}
{#                                                        <img src="{{ reply.author.profile.avatar.url }}" alt="">#}
{#                                                    </div>#}
{#                                                    <div class="we-comment">#}
{#                                                        <div class="coment-head">#}
{#                                                            <h5><a href="{% url 'accounts:profile' reply.author.username %}" title="">{{ comment.author.get_full_name|title }}</a></h5>#}
{#                                                            <span>{{ reply.commented_at }}</span>#}
{#                                                            <a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>#}
{#                                                        </div>#}
{#                                                        <p>{{ reply.comment }}</p>#}
{#                                                    </div>#}
{#                                                </li>#}
{#                                            {% endfor %}#}
{#                                        </ul>#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                            <li class="post-comment">#}
{#                                <div class="comet-avatar">#}
{#                                    <img src="{{ request.user.profile.avatar.url }}" alt="">#}
{#                                </div>#}
{#                                <div class="post-comt-box">#}
{#                                    <form method="post">#}
{#                                        <textarea placeholder="Post your comment"></textarea>#}
{#                                        <div class="add-smiles">#}
{#                                            <span class="em em-expressionless" title="add icon"></span>#}
{#                                        </div>#}
{#                                        <button type="submit"></button>#}
{#                                    </form>#}
{#                                </div>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- centerl meta -->
{% endblock content %}
{% block dashboard %}
    {% include 'courses.html' %}
{% endblock dashboard %}

templates/accounts/email_sent.html
{% extends 'auth_base.html' %}
{% block auth %}
{% block title %}<title> Activation Email Sent </title>{% endblock title %}
{% block navbar %}
 {{ block.super }}
{% endblock navbar %}
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="login-reg-bg">
			<div class="log-reg-area">
				<h2 class="log-title">Activation email sent</h2>
				<form action="" method="post">
					<p>Please confirm your email address to complete the registration</p>
				</form>
			</div>
		</div>
	</div>
{% endblock auth %}

templates/accounts/login.html
{% extends 'auth_base.html' %}
{% block auth %}
{% block title %}<title> Sign In </title>{% endblock title %}
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="login-reg-bg">
            <div class="log-reg-area sign">
                <h2 class="log-title">Sign in</h2>
                <form method="post" action="">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                        <label class="control-label">{{ field.label_tag }}</label><i class="mtrl-select"></i>
                        {% if field.errors %}
                            <small class="text-warning">{{ field.errors }}</small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <small><a class="text-primary" title="" href="{% url 'accounts:password_reset' %}">Forgot Password?</a></small>
                    <div class="submit-btns">
                        <button type="submit" class="mtr-btn"><span>Sign in</span></button>
                    </div>
                    <div class="mt-3">
                        <small class="text-muted">Don't have an account? <a href="{% url 'accounts:register' %}" class="text-primary">Sign up</a></small>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock auth %}

templates/accounts/logout.html
{% extends 'auth_base.html' %}
{% block auth %}
{% block title %}
    <title> Logged Out</title>
{% endblock title %}
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="login-reg-bg">
			<div class="log-reg-area">
				<h2 class="log-title">logged out</h2>
				<form action="" method="post">
					<p>Do you want to check Janice Griffith’s Profile?</p>
					<div class="submit-btns" >
						<a href="{% url 'accounts:login' %}"><button class="btn" type="button">Sign in</button></a>
						<a href="{% url 'accounts:register' %}"><button class="btn" type="button">Sign up</button></a>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock auth %}

templates/accounts/register.html
{% extends 'auth_base.html' %}
{% block auth %}
{% block title %}<title> Create Account</title>{% endblock title %}
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
	<div class="login-reg-bg">
		<div class="log-reg-area">
			<h2 class="log-title">Create Account</h2>
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="form-group">
					{{ field }}
					<label class="control-label" for="input">{{ field.label_tag }}</label><i class="mtrl-select"></i>
					{% if field.errors %}
					{{ field.errors }}
					{% endif %}
				</div>
				{% endfor %}
				<div class="submit-btns">
                    <button type="submit" class="mtr-btn"><span>Create account</span></button>
                </div>
				<div class="mt-3">
					<small class="text-muted">Already have an account? <a href="{% url 'accounts:login' %}" class="text-primary">Sign in instead</a></small>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock auth %}

templates/accounts/social_form.html
{% extends 'base-user-profile.html' %}
{% block content %}
    {% block title %}<title> update Social Profile</title>{% endblock title %}
    <div class="col-lg-6">
        <div class="central-meta">
            <div class="editing-info">
                <h5 class="f-title ext-margin"><i class="ti-share"></i> Your Social Accounts</h5>
                <form method="post">
                {% csrf_token %}
                    {% for field in social %}
                    <div class="form-group">
                      {{ field }}
                      <label class="control-label" for="input"><i class="fa fa-{{ field.name }}-square"></i>{{ field.label_tag }}</label><i class="mtrl-select"></i>
                    </div>
                    {% endfor %}
                    <div class="submit-btns">
                        <button type="submit" class="mtr-btn"><span>Add social accounts</span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- centerl meta -->
{% endblock content %}