accounts/urls.py
from django.urls import path

from accounts.views import (UsersLoginView, UsersLogoutView,
                            email_activate_view, users_signup_view, dashboard,
                            user_account_update_form, user_profile_update_form, user_social_form, PasswordChange,
                            PasswordChangeDone, PasswordReset, PasswordResetDone, PasswordResetConfirm,
                            PasswordResetComplete, UsersProfileView)
app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', users_signup_view, name="register"),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', email_activate_view, name='activate'),
    path('accounts/login/', UsersLoginView.as_view(), name='login'),
    path('accounts/logout/', UsersLogoutView.as_view(), name='logout'),
    path('accounts/account/update/', user_account_update_form, name='user_account_update_form'),
    path('accounts/profile/update/', user_profile_update_form, name='user_profile_update_form'),
    path('accounts/social/update/', user_social_form, name='user_social_form'),
    path('accounts/password/change/', PasswordChange.as_view(), name='password_change'),
    path('accounts/password/change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('accounts/password/reset/', PasswordReset.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', PasswordResetDone.as_view(), name='reset_done'),
    path('accounts/password/reset/complete/', PasswordResetComplete.as_view(), name='reset_complete'),
    path('accounts/password/reset/confirm/<uidb64>/<token>', PasswordResetConfirm.as_view(), name='reset_confirm'),
    path('author/<str:username>/', UsersProfileView.as_view(), name='profile'),
    path('dashboard/', dashboard, name='dashboard'),
]

courses/urls.py
from django.urls import path
from courses.views import CoursesCreateView, CoursesListView, CoursesUpdateView, CoursesDeleteView, \
    SearchView, course_detail

app_name = 'course'
urlpatterns = [
    path('', CoursesListView.as_view(), name="home"),
    path('courses/', CoursesListView.as_view(), name="courses"),
    path('courses/<slug:slug>/', course_detail, name="course_detail"),
    # path('courses/<slug:slug>/', CoursesDetailView.as_view(), name="course_detail"),
    path('create/', CoursesCreateView.as_view(), name="course_create"),
    path('courses/update/<slug:slug>/', CoursesUpdateView.as_view(), name="course_update"),
    path('courses/delete/<slug:slug>/', CoursesDeleteView.as_view(), name="course_delete"),
    path('search/', SearchView.as_view(), name="search"),
]

tinymce/urls.py
from django.conf.urls import url
from .views import spell_check, filebrowser, css, spell_check_callback

urlpatterns = [
    url(r'^spellchecker/$', spell_check, name='tinymce-spellchecker'),
    url(r'^filebrowser/$', filebrowser, name='tinymce-filebrowser'),
    url(r'^tinymce4.css', css, name='tinymce-css'),
    url(r'^spellcheck-callback.js', spell_check_callback, name='tinymce-spellcheck-callback')
]

templates/about_user_profile.html
{% extends 'base-user-profile.html' %}
{#{% block title %}<title>Account Activation Error </title>{% endblock title %}#}
{% block profile %}
    <div class="col-lg-6">
        <div class="central-meta">
            <div class="about">
                <div class="personal">
                    <h5 class="f-title"><i class="ti-info-alt"></i> Personal Info</h5>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                </div>
                <div class="d-flex flex-row mt-2">
                    <ul class="nav nav-tabs nav-tabs--vertical nav-tabs--left" >
                        <li class="nav-item">
                            <a href="#basic" class="nav-link active" data-toggle="tab" >Basic info</a>
                        </li>
                        <li class="nav-item">
                            <a href="#location" class="nav-link" data-toggle="tab" >location</a>
                        </li>
                        <li class="nav-item">
                            <a href="#work" class="nav-link" data-toggle="tab" >work and education</a>
                        </li>
                        <li class="nav-item">
                            <a href="#interest" class="nav-link" data-toggle="tab"  >interests</a>
                        </li>
                        <li class="nav-item">
                            <a href="#lang" class="nav-link" data-toggle="tab" >languages</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="basic" >
                            <ul class="basics">
                                <li><i class="ti-user"></i>sarah grey</li>
                                <li><i class="ti-map-alt"></i>live in Dubai</li>
                                <li><i class="ti-mobile"></i>+1-234-345675</li>
                                <li><i class="ti-email"></i><a href="https://wpkixx.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="3c4553494e515d55507c59515d5550125f5351">[email&#160;protected]</a></li>
                                <li><i class="ti-world"></i>www.yoursite.com</li>
                            </ul>
                        </div>
                        <div class="tab-pane fade" id="location" role="tabpanel">
                            <div class="location-map">
                                <div id="map-canvas"></div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="work" role="tabpanel">
                            <div>

                                <a href="#" title="">Envato</a>
                                <p>work as autohr in envato themeforest from 2013</p>
                                <ul class="education">
                                    <li><i class="ti-facebook"></i> BSCS from Oxford University</li>
                                    <li><i class="ti-twitter"></i> MSCS from Harvard Unversity</li>
                                </ul>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="interest" role="tabpanel">
                            <ul class="basics">
                                <li>Footbal</li>
                                <li>internet</li>
                                <li>photography</li>
                            </ul>
                        </div>
                        <div class="tab-pane fade" id="lang" role="tabpanel">
                            <ul class="basics">
                                <li>english</li>
                                <li>french</li>
                                <li>spanish</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- centerl meta -->
{% endblock profile %}

templates/auth_base.html
{% extends 'styles.html' %}
{% load static %}
{% block body %}
<body>
    <div class="theme-layout">
        <div class="container-fluid pdng0">
            <div class="row merged">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="land-featurearea">
                        <div class="land-meta">
                            <h1>Digglepress</h1>
                            <div class="friend-logo">
                                <span><img src="{% static 'images/wink.png' %}" alt=""></span>
                            </div>
                        </div>
                    </div>
                </div>
                {% block auth %}

                {% endblock auth %}
            </div>
        </div>
    </div>
</body>
{% endblock body %}
</html>

templates/base.html
{% extends 'styles.html' %}
{% load static %}
{% block body %}
{% block title %}
    <title></title>
{% endblock title %}
{% include 'navbar.html' %}
	<section>
		<div class="gap2 gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row merged20" id="page-contents">
							<div class="col-lg-3">
                                {% block sidebar-left %}
                                    {% include 'left_sidebar.html' %}
                                {% endblock sidebar-left %}
							</div>
                            <!-- sidebar left -->
							{% block content %}
                            {% endblock content%}
							<div class="col-lg-3">
                                {% block sidebar-right %}
                                    {% include 'right_sidebar.html' %}
                                {% endblock sidebar-right %}
							</div>
                            <!-- sidebar right -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock footer %}
{% endblock body %}

templates/courses.html
<aside class="sidebar static">
    <div class="widget friend-list stick-widget">
        <h4 class="widget-title">Your Courses </h4>
        <div id="searchDir"></div>
        <ul id="people-list" class="friendz-list">
            {% for course in courses %}
                <li>
                    <figure>
                        <img src="{{ course.cover_sm.url }}" alt="{{ course.author.get_full_name }}">
                    </figure>
                    {% if course.title|wordcount < 40 %}
                        <div class="friendz-meta">
                            <a href="{% url 'course:course_detail' course.slug  %}">{{ course.title|title|truncatechars:40 }}</a>
                            <i>{{ course.published }}</i>
                        </div>
                    {% else %}
                        <div class="friendz-meta">
                            <a href="{% url 'course:course_detail' course.slug  %}">{{ course.title|title }}</a>
                            <i>{{ course.published }}</i>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div><!-- friends list sidebar -->
</aside>

templates/edit_account.html
{% extends 'base-user-profile.html' %}
{% block content %}
<div class="col-lg-6">
    <div class="central-meta">
        <div class="onoff-options">
            <h5 class="f-title"><i class="ti-settings"></i>account setting</h5>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate</p>
            <form method="post">
                <div class="setting-row">
                    <span>Sub users</span>
                    <p>Enable this if you want people to follow you</p>
                    <input type="checkbox" id="switch00" />
                    <label for="switch00" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="setting-row">
                    <span>Enable follow me</span>
                    <p>Enable this if you want people to follow you</p>
                    <input type="checkbox" id="switch01" />
                    <label for="switch01" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="setting-row">
                    <span>Send me notifications</span>
                    <p>Send me notification emails my friends like, share or message me</p>
                    <input type="checkbox" id="switch02" />
                    <label for="switch02" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="setting-row">
                    <span>Text messages</span>
                    <p>Send me messages to my cell phone</p>
                    <input type="checkbox" id="switch03" />
                    <label for="switch03" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="setting-row">
                    <span>Enable tagging</span>
                    <p>Enable my friends to tag me on their posts</p>
                    <input type="checkbox" id="switch04" />
                    <label for="switch04" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="setting-row">
                    <span>Enable sound Notification</span>
                    <p>You'll hear notification sound when someone sends you a private message</p>
                    <input type="checkbox" id="switch05" checked=""/>
                    <label for="switch05" data-on-label="ON" data-off-label="OFF"></label>
                </div>
                <div class="submit-btns">
                    <button type="button" class="mtr-btn"><span>Cancel</span></button>
                    <button type="button" class="mtr-btn"><span>Update</span></button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- centerl meta -->

{% endblock content %}

templates/edit_interest.html
{% extends 'base-user-profile.html' %}
{% block content %}

<div class="col-lg-6">
    <div class="central-meta">
        <div class="editing-interest">
            <h5 class="f-title"><i class="ti-heart"></i>My interests</h5>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate</p>
            <form method="post">
                <label>Add interests: </label>
                <input type="text" placeholder="Photography, Cycling, traveling.">
                <button type="submit">Add</button>
                <ol class="interest-added">
                    <li><a href="#" title="">bycicling</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                    <li><a href="#" title="">traveling</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                    <li><a href="#" title="">photography</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                    <li><a href="#" title="">shopping</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                    <li><a href="#" title="">eating</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                    <li><a href="#" title="">hoteling</a><span class="remove" title="remove"><i class="fa fa-close"></i></span></li>
                </ol>
                <div class="submit-btns">
                    <button type="button" class="mtr-btn"><span>Cancel</span></button>
                    <button type="button" class="mtr-btn"><span>Update</span></button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- centerl meta -->

{% endblock content %}

templates/edit_password.html
{% extends 'base-user-profile.html' %}
{% block content %}
<div class="col-lg-6">
    <div class="central-meta">
        <div class="editing-info">
            <h5 class="f-title"><i class="ti-lock"></i>Change Password</h5>

            <form method="post">
                <div class="form-group">
                  <input type="password" id="input" required="required"/>
                  <label class="control-label" for="input">New password</label><i class="mtrl-select"></i>
                </div>
                <div class="form-group">
                  <input type="password" required="required"/>
                  <label class="control-label" for="input">Confirm password</label><i class="mtrl-select"></i>
                </div>
                <div class="form-group">
                  <input type="password" required="required"/>
                  <label class="control-label" for="input">Current password</label><i class="mtrl-select"></i>
                </div>
                <a class="forgot-pwd underline" title="" href="#">Forgot Password?</a>
                <div class="submit-btns">
                    <button type="button" class="mtr-btn"><span>Cancel</span></button>
                    <button type="button" class="mtr-btn"><span>Update</span></button>
                </div>
            </form>
        </div>
    </div>
</div><!-- centerl meta -->
{% endblock content %}

templates/footer.html
{% load  static %}
<div class="bottombar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <span class="copyright"><a href="{% url 'course:home' %}">Digglepress {% now 'DATE_FORMAT' %}</a></span>
                <i><img src="{% static 'images/credit-cards.png' %}" alt=""></i>
            </div>
        </div>
    </div>
</div>

templates/navbar.html
{% load static %}
{% if request.user.is_authenticated %}
    <div class="topbar stick">
    <div class="logo">
        <a title="" href="{% url 'course:home' %}"><img src="{% static 'images/digglepress.png' %}" alt="digglepress"></a>
    </div>
    <div class="top-area">
        <div class="top-search">
            <form method="get" action="{% url 'course:search' %}" class="">
                <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search Course">
                <button type="submit" data-ripple><i class="ti-search"></i></button>
            </form>
        </div>
        <ul class="setting-area">
            <li>
                <a href="{% url 'course:home' %}" title="Home" data-ripple=""><i class="ti-home"></i></a>
            </li>
            <li>
                <a href="{% url 'course:courses' %}" title="Courses" data-ripple=""><i class="ti-book"></i></a>
            </li>
            <li>
                <a href="{% url 'accounts:dashboard' %}" title="Dashboard" data-ripple=""><i class="ti-dashboard"></i></a>
            </li>
        </ul>
        {% if request.user.profile.avatar %}
            <div class="user-img">
                <img src="{{ request.user.profile.avatar.url }}" alt="{{ request.user.username }}" title="{{ request.user.get_full_name|title }}" >
                <div class="user-setting">
                    <a href="{% url 'accounts:user_profile_update_form' %}" title=""><i class="ti-user"></i>edit profile</a>
                    <a href="{% url 'accounts:user_account_update_form' %}" title=""><i class="ti-settings"></i>edit account</a>
                    <a href="{% url 'accounts:logout' %}"><i class="ti-power-off"></i>log out</a>
                </div>
            </div>
        {% else %}
            <img src="{% static 'default.ico' %}" alt="">
        {% endif %}
        <span class="ti-menu main-menu" data-ripple=""></span>
    </div>
</div>
    <!-- topbar -->
{% else %}
    <div class="topbar stick">
        <div class="logo">
            <a href="{% url 'course:courses' %}"><img src="{% static 'images/digglepress.png' %}" alt="{{ domain }}"></a>
        </div>
        <div class="top-area">
            <div class="login-form">
                <form action="" method="post">
                    <a href="{% url 'accounts:login' %}"><button type="button">Sign in</button></a>
                    <a href="{% url 'accounts:register' %}"><button type="button">Create account</button></a>
                </form>
            </div>
        </div>
    </div>
{% endif %}

templates/right_sidebar.html
{% load static %}
<aside class="sidebar static right">
    {% if request.user.is_authenticated %}
    <div class="widget">
        <div class="your-page author-board pt-4">
            <figure>
                <img src="{{ request.user.profile.avatar_large.url }}" alt="">
            </figure>
            <div class="page-likes">
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active fade show " >
                        <h5>{{ request.user.get_full_name|title }}</h5>
                          <p>{{ request.user.profile.profession|title }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- page like widget -->
    <div class="widget">
        <div class="banner medium-opacity bluesh">
            <div class="bg-image" style="background-image: url({% static 'images/resources/baner-widgetbg.jpg' %})"></div>
            <div class="baner-top">
                <span><img alt="" src="{% static 'images/book-icon.png' %}"></span>
                <i class="fa fa-ellipsis-h"></i>
            </div>
            <div class="banermeta">
                <p>
                    create course.
                </p>
                <a data-ripple="" title="" href="{% url 'course:course_create'%}">Create Course!</a>
            </div>
        </div>
    </div>
        <div class="widget stick-widget">
            <h4 class="widget-title">{{ request.user.get_full_name|title }}</h4>
            <ul class="short-profile">
                {% if request.user.profile.bio %}
                    <li>
                        <span>about</span>
                        <p>{{ request.user.profile.bio|capfirst }}</p>
                    </li>
                {% endif %}
                {% if request.user.profile.city and request.user.profile.country %}
                    <li>
                        <span>Location</span>
                        <p>{{ request.user.profile.get_location|title }}</p>
                    </li>
                {% endif %}
                {% if request.user.profile.profession %}
                    <li>
                        <span>Profession</span>
                        <p>{{ request.user.profile.profession|capfirst }}</p>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
</aside>

templates/styles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    {% block title %}
        <title></title>
    {% endblock title %}
    <link rel="icon" href="{% static 'images/fav.png' %}" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'tinymce/css/prism.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {{ form.media }}
</head>
<body>
    {% block body %}

    {% endblock body %}
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'tinymce/js/prism.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/echarts.min.js' %}"></script>
	<script src="{% static 'js/file-upload.js' %}"></script>
	<script src="{% static 'js/userincr.js' %}"></script>
	<script src="{% static 'js/reply.js' %}"></script>
</body>
</html>