accounts/urls.py
from django.urls import path

from accounts.views import (UsersLoginView, UsersLogoutView,
                            email_activate_view, users_signup_view, dashboard,
                            user_account_update_form, user_profile_update_form, user_social_form, PasswordChange,
                            PasswordChangeDone, PasswordReset, PasswordResetDone, PasswordResetConfirm,
                            PasswordResetComplete, UsersProfileView)
app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', users_signup_view, name="register"),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', email_activate_view, name='activate'),
    path('accounts/login/', UsersLoginView.as_view(), name='login'),
    path('accounts/logout/', UsersLogoutView.as_view(), name='logout'),
    path('accounts/account/update/', user_account_update_form, name='user_account_update_form'),
    path('accounts/profile/update/', user_profile_update_form, name='user_profile_update_form'),
    path('accounts/social/update/', user_social_form, name='user_social_form'),
    path('accounts/password/change/', PasswordChange.as_view(), name='password_change'),
    path('accounts/password/change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('accounts/password/reset/', PasswordReset.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', PasswordResetDone.as_view(), name='reset_done'),
    path('accounts/password/reset/complete/', PasswordResetComplete.as_view(), name='reset_complete'),
    path('accounts/password/reset/confirm/<uidb64>/<token>', PasswordResetConfirm.as_view(), name='reset_confirm'),
    path('author/<str:username>/', UsersProfileView.as_view(), name='profile'),
    path('dashboard/', dashboard, name='dashboard'),
]

courses/urls.py
from django.urls import path
from courses.views import CoursesCreateView, CoursesListView, CoursesUpdateView, CoursesDeleteView, \
    SearchView, course_detail

app_name = 'course'
urlpatterns = [
    path('', CoursesListView.as_view(), name="home"),
    path('courses/', CoursesListView.as_view(), name="courses"),
    path('courses/<slug:slug>/', course_detail, name="course_detail"),
    # path('courses/<slug:slug>/', CoursesDetailView.as_view(), name="course_detail"),
    path('create/', CoursesCreateView.as_view(), name="course_create"),
    path('courses/update/<slug:slug>/', CoursesUpdateView.as_view(), name="course_update"),
    path('courses/delete/<slug:slug>/', CoursesDeleteView.as_view(), name="course_delete"),
    path('search/', SearchView.as_view(), name="search"),
]

tinymce/urls.py
from django.conf.urls import url
from .views import spell_check, filebrowser, css, spell_check_callback

urlpatterns = [
    url(r'^spellchecker/$', spell_check, name='tinymce-spellchecker'),
    url(r'^filebrowser/$', filebrowser, name='tinymce-filebrowser'),
    url(r'^tinymce4.css', css, name='tinymce-css'),
    url(r'^spellcheck-callback.js', spell_check_callback, name='tinymce-spellcheck-callback')
]

courses/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from courses.utilities import course_slug
from django.db.models.signals import pre_save
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from tinymce.models import HTMLField

User = get_user_model()


class Courses(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    cover = ProcessedImageField(upload_to='courses_featured_image', processors=[ResizeToFill(600, 300)],
                                format='png', options={'quality': 80}, blank=True)
    cover_sm = ImageSpecField(source='cover',
                              processors=[ResizeToFill(600, 600)],
                              format='png',
                              options={'quality': 100})
    slug = models.SlugField()
    title = models.CharField(max_length=200)
    body = HTMLField()
    # body = models.TextField()
    summary = models.CharField(max_length=300)
    published = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Courses'

    def __str__(self):
        return '{} {}'.format(self.author.username, self.title)

    def get_absolute_url(self):
        return reverse('course:course_detail', kwargs={'slug': self.slug})


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = course_slug(instance, instance.title, instance.slug)


pre_save.connect(slug_save, sender=Courses)


class Comments(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    comment = models.TextField()
    commented_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='reply')
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ('-commented_at',)
        verbose_name_plural = 'Comments'

    def __str__(self):
        return "{}".format(self.author)

courses/forms.py
from django import forms
from courses.models import Courses, Comments
from tinymce.widgets import TinyMCE


class CourseCreateForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(mce_attrs={'width': 750, 'class': 'form-group'}))

    class Meta:
        model = Courses
        fields = ['cover', 'title', 'summary', 'body']


class CommentsForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 5,
            'cols': 10
        }
    ))

    class Meta:
        fields = ['comment']
        model = Comments

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from courses.forms import CommentsForm, CourseCreateForm
from courses.models import Comments, Courses
from django.contrib.auth import get_user_model

User = get_user_model()


def page_not_found(request, exception):
    return render(request, '404.html', status=404)


class CoursesListView(ListView):
    template_name = 'courses/course_list.html'
    model = Courses
    ordering = ['-published']
    paginate_by = 5

    def get_context_data(self, *args, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context['side_course'] = Courses.objects.filter().order_by('-published')[:5]
        context['users'] = User.objects.exclude(id=self.request.user.id)
        return context


# class CoursesDetailView(DetailView):
#     template_name = 'courses/course_detail.html'
#     context_object_name = 'course_detail'
#     model = Courses

def course_detail(request, slug):
    course = get_object_or_404(Courses, slug=slug)
    comments = course.comments.filter(active=True, parent__isnull=True)
    if request.method == 'POST':
        comment_form = CommentsForm(data=request.POST)
        if comment_form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comments.objects.get(id=parent_id)
                if parent_obj:
                    replay_comment = comment_form.save(commit=False)
                    replay_comment.parent = parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.course = course
            new_comment.author = request.user
            new_comment.save()
            return HttpResponseRedirect(course.get_absolute_url())
    else:
        comment_form = CommentsForm()
    context = {'course_detail': course,
               'comments': comments,
               'comment_form': comment_form}
    return render(request, 'courses/course_detail.html', context)


class CoursesCreateView(LoginRequiredMixin, CreateView):
    template_name = 'courses/course_form.html'
    model = Courses
    form_class = CourseCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CoursesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'courses/course_form.html'
    model = Courses
    form_class = CourseCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.author:
            return True
        return False


class CoursesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'courses/course_delete.html'
    model = Courses
    success_url = reverse_lazy('accounts:dashboard')

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.author:
            return True
        return False


class SearchView(ListView):
    model = Courses
    template_name = 'courses/course_search.html'
    context_object_name = 'search_list'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            result = Courses.objects.filter(
                Q(title__icontains=query) |
                Q(summary__icontains=query)
            )
        else:
            result = Courses.objects.all()
        return result

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')

        return context


class BaseTemplateView(ListView):
    model = Courses
    template_name = 'base.html'

templates/courses/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block sidebar-left %}
    {{ block.exclude }}
{% endblock sidebar-left %}
{% block sidebar-right %}
    {{ block.exclude }}
{% endblock sidebar-right %}
{% block content %}
{% block title %}
    <title>{{ course_detail.title }}</title>
{% endblock title %}
<div class="theme-layout">
    <section>
        <div class="gap ext-bottom">
            <div class="container">
                <div class="row">
                    <div class="offset-lg-1 col-lg-10">
                        <div class="detail-page">
                            <div class="detail-top">
                                <img src="{{ course_detail.cover.url }}" class="container-fluid" alt="">
                                    <div class="connect-with">
                                        <ul class="social-connect">
                                            <li class="rs">
                                                <i class="fa fa-rss"></i>
                                                <span>
                                                    <a title="" href="#">Subscribe</a>
                                                    <i>to Rss Feed</i>
                                                </span>
                                            </li>
                                            <li class="twit">
                                                <i class="fa fa-twitter"></i>
                                                <span>
                                                    <a title="" href="#">Follow Us</a>
                                                    <i>on twitter</i>
                                                </span>
                                            </li>
                                            <li class="fb">
                                                <i class="fa fa-facebook"></i>
                                                <span>
                                                    <a title="" href="#">Find Us</a>
                                                    <i>on Facebook</i>
                                                </span>
                                            </li>
                                            <li class="googl">
                                                <i class="fa fa-google-plus"></i>
                                                <span>
                                                    <a title="" href="#">Find Us</a>
                                                    <i>on Google plus</i>
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            <div class="detail-meta">
                                <h5>{{ course_detail.title|title }}</h5>
                                <div class="post-time">
                                    <div class="author-thumb">
                                        {% if course_detail.author.profile.avatar %}
                                            <img src="{{ course_detail.author.profile.avatar.url }}" alt="">
                                        {% else %}
                                            <img src="{% static 'default.ico' %}" alt="">
                                        {% endif %}
                                        <span><a href="{% url 'accounts:profile' course_detail.author.username %}" title="">By {{ course_detail.author.first_name|capfirst }}</a></span>
                                    </div>
                                    <span class="post-date">
                                        <i class="fa fa-calendar"></i>
                                        <a title="" href="#">{{ course_detail.published }}</a>
                                    </span>
                                    <span class="coments">
                                        <i class="fa fa-comments"></i>
                                        <a title="" href="#">{{ comments.count }}</a>
                                    </span>
                                </div>
                                <p>
                                    {{ course_detail.body|capfirst | safe }}
                                </p>
                                <div class="tag-n-cat">
                                    <div class="tags">
                                        <span><i class="fa fa-tags"></i> Post Tags:</span>
                                        <a href="#" title="">News</a>
                                        <a href="#" title="">ideas</a>
                                        <a href="#" title="">collection</a>
                                        <a href="#" title="">exclusive</a>
                                        <a href="#" title="">features</a>
                                    </div>
                                    <div class="tags">
                                        <span><i class="fa fa-filter"></i> Post Categories:</span>
                                        <a href="#" title="">News</a>
                                        <a href="#" title="">ideas</a>
                                        <a href="#" title="">collection</a>
                                        <a href="#" title="">exclusive</a>
                                        <a href="#" title="">features</a>
                                    </div>
                                </div>
                                {% if course_detail.author.profile.bio %}
                                    <div class="gap-60">
                                        <div class="site-admin">
                                            <div class="admin-avatar">
                                                <img src="{{ course_detail.author.profile.avatar_large.url }}" alt="">
                                            </div>
                                            <div class="admin-postmeta">
                                                <h4>{{ course_detail.author.get_full_name|title }}</h4>
                                                <span>{{ course_detail.author.profile.profession }}</span>
                                                <p>
                                                    {{ course_detail.author.profile.bio }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="gap-60 no-top">
                                    <div class="comment-area">
                                        <h4 class="comment-title">{{ comments.count }} comments</h4>
                                        <ul class="comments">
                                            {% for comment in comments %}
                                                <li>
                                                    <div class="comment-box">
                                                        <div class="commenter-photo">
                                                            <img alt="" src="{{ comment.author.profile.avatar.url }}">
                                                        </div>
                                                        <div class="commenter-meta">
                                                            <div class="comment-titles">
                                                                <h6>{{ comment.author.get_full_name|title }}</h6>
                                                                <span>{{ comment.commented_at }}</span>
                                                            </div>
                                                            <p>{{ comment.comment }}</p>
                                                        </div>
                                                        <button type="button" name="button" class="reply-btn btn-primary btn-sm float-right" ><i>Reply</i></button>
                                                    </div>
                                                    <ul class="replies" style="display: none">
                                                        {% for reply in comment.reply.all %}
                                                            <li>
                                                                <div class="comment-box">
                                                                    <div class="commenter-photo">
                                                                        <img alt="" src="{{ reply.author.profile.avatar.url }}">
                                                                    </div>
                                                                    <div class="commenter-meta">
                                                                        <div class="comment-titles">
                                                                            <h6>{{ reply.author.get_full_name|title }}</h6>
                                                                            <span>{{ reply.commented_at|time }}</span>
                                                                        </div>
                                                                        <p>{{ reply.comment }}</p>
                                                                    </div>
                                                                </div>
                                                            </li>
                                                        {% endfor %}
                                                    <h5>Reply</h5>
                                                    <form action="." method="post">
                                                        {{ comment_form.as_p }}
                                                        {% csrf_token %}
                                                        <!-- Hidden input for parent comment.id -->
                                                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                                        <button class="mtr-btn" type="submit"><i>Reply</i></button>
                                                    </form>
                                                    </ul>
                                                </li>
                                            {% empty %}
                                                <h4>Be the first to comment on this course.</h4>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <!-- comments sec -->
                                {% if request.user.is_authenticated %}
                                    <div class="gap-60 no-gap">
                                        <h4 class="comment-title">Leave a Comment</h4>
                                        <div class="contact-form">
                                            <form action="." method="post">
                                                {% csrf_token %}
                                                {% for form in comment_form %}
                                                    <div class="form-group">
                                                        {{ form }}
                                                        <label class="control-label" for="input">{{ form.label }}</label><i class="mtrl-select"></i>
                                                    </div>
                                                {% endfor %}
                                                <div class="submit-btns">
                                                    <button class="mtr-btn" type="submit"><i>Comment</i></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                {% else %}
                                    <a href="{% url 'accounts:login' %}"><h4 class="comment-title">Sign in to post a comment</h4></a>
                                <!-- comment form -->
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% block title %}
    <title>Digglepress Courses</title>
{% endblock title %}
<div class="col-lg-6">
{% for course in courses_list %}
        <div class="central-meta item">
            <div class="user-post">
                <div class="friend-info">
                {% if course.author.profile.avatar %}
                    <figure>
                        <img src="{{ course.author.profile.avatar.url }}" alt="">
                    </figure>
                {% else %}
                    <img src="{% static 'default.ico' %}" alt="">
                {% endif %}
                    <div class="friend-name">
                        <ins><a href="{% url 'accounts:profile' course.author.username %}" title="">{{ course.author.get_full_name|title }}</a></ins>
                        <span>published: {{ course.published }}</span>
                    </div>
                    <div class="post-meta">
                        {% if course.cover %}
                            <img src="{{ course.cover.url }}" alt="">
                        {% endif %}
                        <div class="we-video-info">
                            <ul>
                                <li>
                                    <span class="views" data-toggle="tooltip" title="views">
                                        <i class="fa fa-eye"></i>
                                        <ins>1.2k</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="comment" data-toggle="tooltip" title="Comments">
                                        <i class="fa fa-comments-o"></i>
                                        {% if course.comments %}
                                            <ins>{{ course.comments.count }}</ins>
                                        {% endif %}
                                    </span>
                                </li>
                                <li>
                                    <span class="like" data-toggle="tooltip" title="like">
                                        <i class="ti-heart"></i>
                                        <ins>2.2k</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="dislike" data-toggle="tooltip" title="dislike">
                                        <i class="ti-heart-broken"></i>
                                        <ins>200</ins>
                                    </span>
                                </li>
                                <li class="social-media">
                                    <div class="menu">
                                      <div class="btn trigger"><i class="fa fa-share-alt"></i></div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-html5"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-facebook"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-google-plus"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-twitter"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-css3"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-instagram"></i></a>
                                        </div>
                                      </div>
                                        <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-dribbble"></i></a>
                                        </div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-pinterest"></i></a>
                                        </div>
                                      </div>

                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="friend-name">
                            <ins><a href="{{ course.get_absolute_url }}" title="">{{ course.title|title }}</a></ins>
                        </div>
                        <div class="description">
                            <p><span>{{ course.summary|capfirst }}</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endfor %}
{% if is_paginated %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"><button class="btn-view btn-load-more">Load More</button></a>
    {% endif %}
{% endif %}
</div>
{% endblock content %}

templates/courses/course_search.html
{% extends 'base.html' %}
{% load static %}
{% block sidebar-left %}
    {{ block.exclude }}
{% endblock sidebar-left %}
{% block sidebar-right %}
    {{ block.exclude }}
{% endblock sidebar-right %}
{% block footer %}
    {{ block.super }}
{% endblock footer %}
{% block content %}
{% block title %}
    <title>Result for "{{ query }}"</title>
{% endblock title %}
<div class="theme-layout">
	<section>
		<div class="gap gray-bg">
			<div class="container">
				<div class="row" id="page-contents">
					<div class=" col-lg-12">
						<div class="blog-sec">
							<div class="row">
                                {% for course in search_list %}
                                    <div class="col-lg-4 col-sm-6">
                                        <div class="g-post-classic">
                                            <figure>
                                                <img alt="" src="{{ course.cover.url }}">
                                            </figure>
                                            <div class="g-post-meta">
                                                <div class="post-title">
                                                    <h4><a title="" href="{{ course.get_absolute_url }}">{{ course.title|title }}</a></h4>
                                                    <p>{{ course.summary|truncatewords:20|capfirst }}</p>
                                                    <span class="p-date">by <a href="{% url 'accounts:profile' course.author.username %}" title="">{{ course.author.get_full_name|title }}
                                                    </a> - {{ course.published }}</span>
                                                </div>
                                                <div class="g-post-ranking">
                                                    <a title="" href="#" class="likes"><i class="fa fa-heart-o"></i>10 likes</a>
                                                    <a title="" href="#" class="coments"><i class="fa fa-comment-o"></i>{{ course.comments.count }} comment{{ course.comments.count|pluralize }}</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% empty %}
                                    <h6>
                                        No course matches your query.
                                    </h6>
								{% endfor %}
							</div>
                            {% if is_paginated %}
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}"><button class="btn-view btn-load-more">Load More</button></a>
                                {% endif %}
                            {% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
{% endblock content %}